name: CI

on:
    push:
        branches: ["main"]

jobs:
    build:
        name: PR Verify
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 10.0
                        
            - name: Run tests
              run: dotnet test --configuration Release

            - name: Publish
              run: dotnet publish src/GitHubActionsDotNet.API/GitHubActionsDotNet.API.csproj --configuration Release -o artifactcs
